apiVersion: v1
kind: Secret
metadata:
  name: nestjs-secret
type: Opaque
data:
  KAFKA_CLIENT_ID: <inclua seu secret em base64 (echo -n "****" | base64)>
  KAFKA_HOST: <inclua seu secret em base64 (echo -n "****" | base64)>
  KAFKA_USE_SSL: <inclua seu secret em base64 (echo -n "****" | base64)>
  KAFKA_CONSUMER_GROUP_ID: <inclua seu secret em base64 (echo -n "****" | base64)>
  KAFKA_SASL_USERNAME: <inclua seu secret em base64 (echo -n "****" | base64)>
  KAFKA_SASL_PASSWORD: <inclua seu secret em base64 (echo -n "****" | base64)>
  KAFKA_CONNECTION_TIMEOUT: <inclua seu secret em base64 (echo -n "****" | base64)>
  NEXT_HOST: <inclua seu secret em base64 (echo -n "****" | base64)>
  MONGO_DSN: <inclua seu secret em base64 (echo -n "****" | base64)>
  REDIS_HOST: <inclua seu secret em base64 (echo -n "****" | base64)>
  REDIS_PORT: <inclua seu secret em base64 (echo -n "****" | base64)>
  REDIS_PASSWORD: <inclua seu secret em base64 (echo -n "****" | base64)>